package ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ai_based_medical_chatbot.data.api.PredictionRequest
import com.example.ai_based_medical_chatbot.data.api.RetrofitClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext


data class ChatMessage(
    val text: String,
    val isUser: Boolean
)

@Composable
fun ChatbotScreen(
    onBackClick: () -> Unit = {}
) {

    var message by remember {
        mutableStateOf("")
    }

    var isTyping by remember {
        mutableStateOf(false)
    }

    val messages = remember {
        mutableStateListOf<ChatMessage>()
    }

    /*
     * ============================================================
     * SEND MESSAGE
     * ============================================================
     */

    fun sendMessage(text: String) {

        val cleanText = text.trim()

        if (cleanText.isEmpty() || isTyping) {
            return
        }

        messages.add(
            ChatMessage(
                text = cleanText,
                isUser = true
            )
        )

        message = ""
        isTyping = true

        CoroutineScope(Dispatchers.IO).launch {

            try {

                val response = RetrofitClient.api.predict(
                    PredictionRequest(
                        text = cleanText
                    )
                )

                withContext(Dispatchers.Main) {

                    if (response.isSuccessful && response.body() != null) {

                        val result = response.body()!!

                        val confidencePercent =
                            (result.confidence * 100).toInt()

                        val aiMessage =
                            """
                            Intent: ${result.intent}
                            
                            Confidence: $confidencePercent%
                            
                            This result is generated by the MedAssist AI model.
                            Please use this information for educational purposes only.
                            """.trimIndent()

                        messages.add(
                            ChatMessage(
                                text = aiMessage,
                                isUser = false
                            )
                        )

                    } else {

                        messages.add(
                            ChatMessage(
                                text = "Sorry, I could not process your request. Please try again.",
                                isUser = false
                            )
                        )
                    }

                    isTyping = false
                }

            } catch (e: Exception) {

                withContext(Dispatchers.Main) {

                    messages.add(
                        ChatMessage(
                            text = "Unable to connect to the medical AI server. Please make sure the Flask API is running.",
                            isUser = false
                        )
                    )

                    isTyping = false
                }
            }
        }
    }

    /*
     * ============================================================
     * APP COLORS
     * ============================================================
     */

    val primary = Color(0xFF087EA4)
    val darkBlue = Color(0xFF123A56)
    val gray = Color(0xFF71818C)
    val lightBlue = Color(0xFFEAF8FC)
    val lightBlueBottom = Color(0xFFD8F0F6)

    /*
     * ============================================================
     * MAIN SCREEN
     * ============================================================
     */

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(
                        lightBlue,
                        lightBlueBottom
                    )
                )
            )
    ) {

        Column(
            modifier = Modifier.fillMaxSize()
        ) {

            /*
             * ====================================================
             * HEADER
             * ====================================================
             */

            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(
                    bottomStart = 25.dp,
                    bottomEnd = 25.dp
                ),
                colors = CardDefaults.cardColors(
                    containerColor = Color.White
                ),
                elevation = CardDefaults.cardElevation(
                    defaultElevation = 7.dp
                )
            ) {

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(
                            horizontal = 12.dp,
                            vertical = 12.dp
                        ),
                    verticalAlignment = Alignment.CenterVertically
                ) {

                    IconButton(
                        onClick = onBackClick
                    ) {

                        Text(
                            text = "‹",
                            color = darkBlue,
                            fontSize = 40.sp,
                            fontWeight = FontWeight.Light
                        )
                    }

                    Box(
                        modifier = Modifier
                            .size(50.dp)
                            .background(
                                color = Color(0xFFE8F7FB),
                                shape = CircleShape
                            ),
                        contentAlignment = Alignment.Center
                    ) {

                        Text(
                            text = "AI",
                            color = primary,
                            fontSize = 17.sp,
                            fontWeight = FontWeight.Bold
                        )
                    }

                    Spacer(
                        modifier = Modifier.width(12.dp)
                    )

                    Column {

                        Text(
                            text = "AI Medical Assistant",
                            color = darkBlue,
                            fontSize = 19.sp,
                            fontWeight = FontWeight.Bold
                        )

                        Spacer(
                            modifier = Modifier.height(3.dp)
                        )

                        Text(
                            text = "Your intelligent health companion",
                            color = gray,
                            fontSize = 11.sp
                        )
                    }
                }
            }

            /*
             * ====================================================
             * CHAT AREA
             * ====================================================
             */

            Box(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
            ) {

                if (messages.isEmpty()) {

                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(20.dp),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {

                        Spacer(
                            modifier = Modifier.height(30.dp)
                        )

                        Box(
                            modifier = Modifier
                                .size(85.dp)
                                .background(
                                    color = Color.White,
                                    shape = CircleShape
                                ),
                            contentAlignment = Alignment.Center
                        ) {

                            Text(
                                text = "AI",
                                color = primary,
                                fontSize = 25.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }

                        Spacer(
                            modifier = Modifier.height(18.dp)
                        )

                        Text(
                            text = "How can I help you today?",
                            color = darkBlue,
                            fontSize = 21.sp,
                            fontWeight = FontWeight.Bold
                        )

                        Spacer(
                            modifier = Modifier.height(7.dp)
                        )

                        Text(
                            text = "Ask me about symptoms, medicines,\ndiseases or general health information.",
                            color = gray,
                            fontSize = 13.sp
                        )

                        Spacer(
                            modifier = Modifier.height(25.dp)
                        )

                        Text(
                            text = "Try asking",
                            color = darkBlue,
                            fontSize = 15.sp,
                            fontWeight = FontWeight.Bold
                        )

                        Spacer(
                            modifier = Modifier.height(10.dp)
                        )

                        SuggestedQuestion(
                            text = "What are the symptoms of fever?",
                            onClick = {
                                sendMessage(
                                    "What are the symptoms of fever?"
                                )
                            }
                        )

                        SuggestedQuestion(
                            text = "What causes headache?",
                            onClick = {
                                sendMessage(
                                    "What causes headache?"
                                )
                            }
                        )

                        SuggestedQuestion(
                            text = "How can I improve my health?",
                            onClick = {
                                sendMessage(
                                    "How can I improve my health?"
                                )
                            }
                        )
                    }

                } else {

                    LazyColumn(
                        modifier = Modifier.fillMaxSize(),
                        contentPadding = PaddingValues(
                            horizontal = 14.dp,
                            vertical = 14.dp
                        ),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {

                        items(messages) { chatMessage ->

                            ChatBubble(
                                message = chatMessage
                            )
                        }

                        if (isTyping) {

                            item {

                                TypingIndicator()
                            }
                        }
                    }
                }
            }

            /*
             * ====================================================
             * DISCLAIMER
             * ====================================================
             */

            Text(
                text = "⚠ Medical information is for educational purposes only.",
                color = gray,
                fontSize = 10.sp,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(
                        horizontal = 16.dp,
                        vertical = 4.dp
                    )
            )

            /*
             * ====================================================
             * MESSAGE INPUT
             * ====================================================
             */

            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(
                    topStart = 24.dp,
                    topEnd = 24.dp
                ),
                colors = CardDefaults.cardColors(
                    containerColor = Color.White
                ),
                elevation = CardDefaults.cardElevation(
                    defaultElevation = 8.dp
                )
            ) {

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(
                            horizontal = 12.dp,
                            vertical = 10.dp
                        ),
                    verticalAlignment = Alignment.CenterVertically
                ) {

                    OutlinedTextField(
                        value = message,

                        onValueChange = {
                            message = it
                        },

                        modifier = Modifier.weight(1f),

                        placeholder = {
                            Text(
                                text = "Ask something..."
                            )
                        },

                        singleLine = true,

                        enabled = !isTyping,

                        shape = RoundedCornerShape(17.dp),

                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = primary,
                            unfocusedBorderColor = Color(0xFFD8E5E9),
                            cursorColor = primary
                        )
                    )

                    Spacer(
                        modifier = Modifier.width(7.dp)
                    )

                    Box(
                        modifier = Modifier
                            .size(50.dp)
                            .background(
                                color =
                                    if (
                                        message.trim().isNotEmpty() &&
                                        !isTyping
                                    ) {
                                        primary
                                    } else {
                                        Color(0xFFB7CBD1)
                                    },
                                shape = CircleShape
                            ),
                        contentAlignment = Alignment.Center
                    ) {

                        IconButton(
                            onClick = {
                                sendMessage(message)
                            },
                            enabled =
                                message.trim().isNotEmpty() &&
                                        !isTyping
                        ) {

                            Text(
                                text = "➤",
                                color = Color.White,
                                fontSize = 22.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                }
            }
        }
    }
}


/*
 * ================================================================
 * SUGGESTED QUESTION
 * ================================================================
 */

@Composable
fun SuggestedQuestion(
    text: String,
    onClick: () -> Unit
) {

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(
                vertical = 4.dp
            ),
        shape = RoundedCornerShape(17.dp),
        colors = CardDefaults.cardColors(
            containerColor = Color.White
        ),
        elevation = CardDefaults.cardElevation(
            defaultElevation = 3.dp
        )
    ) {

        TextButton(
            onClick = onClick,
            modifier = Modifier.fillMaxWidth()
        ) {

            Text(
                text = text,
                color = Color(0xFF087EA4),
                fontSize = 13.sp
            )
        }
    }
}


/*
 * ================================================================
 * CHAT BUBBLE
 * ================================================================
 */

@Composable
fun ChatBubble(
    message: ChatMessage
) {

    val primary = Color(0xFF087EA4)
    val darkBlue = Color(0xFF123A56)

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement =
            if (message.isUser) {
                Arrangement.End
            } else {
                Arrangement.Start
            }
    ) {

        Box(
            modifier = Modifier
                .fillMaxWidth(0.82f)
                .background(
                    color =
                        if (message.isUser) {
                            primary
                        } else {
                            Color.White
                        },
                    shape = RoundedCornerShape(
                        topStart = 18.dp,
                        topEnd = 18.dp,
                        bottomStart =
                            if (message.isUser) {
                                18.dp
                            } else {
                                5.dp
                            },
                        bottomEnd =
                            if (message.isUser) {
                                5.dp
                            } else {
                                18.dp
                            }
                    )
                )
                .padding(14.dp)
        ) {

            Text(
                text = message.text,

                color =
                    if (message.isUser) {
                        Color.White
                    } else {
                        darkBlue
                    },

                fontSize = 14.sp,

                lineHeight = 20.sp
            )
        }
    }
}


/*
 * ================================================================
 * TYPING INDICATOR
 * ================================================================
 */

@Composable
fun TypingIndicator() {

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(start = 4.dp),

        verticalAlignment =
            Alignment.CenterVertically
    ) {

        Box(
            modifier = Modifier
                .background(
                    color = Color.White,
                    shape = RoundedCornerShape(17.dp)
                )
                .padding(
                    horizontal = 16.dp,
                    vertical = 11.dp
                )
        ) {

            Text(
                text = "AI is typing...",
                color = Color(0xFF71818C),
                fontSize = 12.sp
            )
        }
    }
}